### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by siyangxie** [microsoft/SoftTeacher#1]
Hello!

Just wanna know when the code will be released?

Thanks.

**Comment by SUYEgit** [comment]
+1

**Comment by stupidZZ** [comment]
Thank you for your attention to our work. We are cleaning up the code and verifying the cleaned code to ensure that the experiments are reproducible. We will release the code very soon, an ETA but not a guaranteed date will be early Sep.

Our initial plan is to release all models and scripts of Faster R-CNN with R-50 backbone on COCO-Partial settings and COCO-Full settings. The models/scripts of the stronger detector will be released later after we verify their reproducibility, and it will take some time.

**Comment by Jack-Hu-2001** [comment]
Thanks! I really appreciate your work and am waiting for your code release!

**Comment by stupidZZ** [comment]
Hi all, the code, all models on the **partially labeled data** settings, and most of the Faster R-CNN(R50) models on the **full labeled data** setting have been released! The remaining models **full labeled data** setting will also be released soon!

Thank you again for your patience and interest in our work!

**Comment by yohann84L** [comment]
Thanks a lot @stupidZZ !

**Comment by Jack-Hu-2001** [comment]
Thanks a lot! I wonder if it's a repository based on mmdetection.If so, need I add your code to a mmdetection package?
If you have time, maybe you could add a "train-custom-data-tutorial" and I would be grealy thankful for that.
Thanks again for your code release and I'm excited to learn from your work!

**Comment by Jack-Hu-2001** [comment]
Thanks for your solid work and I have even seen your tutorial! That's really user-friendly!
