### ISSUE TITLE
Inquiry on localization reliability

### ISSUE THREAD

**Issue by nijkah** [microsoft/SoftTeacher#107]
I guess some mismatches using localization reliability between provided code and the paper.

In section 3.3 Box Jittering of the paper, authors seem to say they use localization reliability instead of foreground score.

https://github.com/microsoft/SoftTeacher/blob/4c053b32d30f3685e553a386dc5234145e494713/ssod/models/soft_teacher.py#L399
But it looks like, it only concatenates the predicted box and localization reliability per [x1, y1, x2, y2].
Actually, it does not seem to be averaged contrary to equation 8.

Moreover, these concatenated elements are not used in the loss,
https://github.com/microsoft/SoftTeacher/blob/4c053b32d30f3685e553a386dc5234145e494713/ssod/models/soft_teacher.py#L198
https://github.com/microsoft/SoftTeacher/blob/4c053b32d30f3685e553a386dc5234145e494713/ssod/models/soft_teacher.py#L272

I also could not find the selection process of the teacher generated pseudo boxes.

Is there something I am missing?

**Comment by MendelXu** [comment]
It is done here. https://github.com/microsoft/SoftTeacher/blob/4c053b32d30f3685e553a386dc5234145e494713/ssod/models/soft_teacher.py#L270

**Comment by nijkah** [comment]
> It is done here.
> 
> https://github.com/microsoft/SoftTeacher/blob/4c053b32d30f3685e553a386dc5234145e494713/ssod/models/soft_teacher.py#L270

Thank you. I got the point.
