### ISSUE TITLE
ICCV2021 accepted? VOC?

### ISSUE THREAD

**Issue by zen-star** [microsoft/SoftTeacher#11]
Good job!
Wonder whether this work is accepted by iccv2021?
Any experiments on PASCAL VOC?

THX.

**Comment by MendelXu** [comment]
Yes, it is accepted by iccv2021. We didn't include experiments on PASCAl VOC. But I think it should be simple to conduct such experiments.

**Comment by zen-star** [comment]
Gocha. 
Have you ever tried single-scale training for a fair comparison with STAC/Unbiased Teacher...? It is critical and may weaken your advantages, I think.

**Comment by MendelXu** [comment]
We have conducted a baseline following STAC using the same augmentation in our paper (See `Multi-stage` in Table 6).  Maybe it is better to run with the official code. But I have to say it is a little hard to run a TensorFlow project.

**Comment by zen-star** [comment]
Thanks for your time^^

**Comment by MendelXu** [comment]
You are welcome. If you have other questions on semi-supervised object detection related or not to our paper, you can still open an issue here.😂
