### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by qdd1234** [microsoft/SoftTeacher#119]
![image](https://user-images.githubusercontent.com/68497831/143375147-e20ab987-d2d1-4178-a59d-ca18572f7b5f.png)
您好，我按照您提供的准备数据脚本的代码下载好数据，并运行您提供的使用10%有标签数据，但是一直报缺少图片的错误，我想问一下这是什么原因？

**Comment by MendelXu** [comment]
你可以`ls -l /home/kkk/coco/train2017|grep xxxxx`看看有没有这张图片

**Comment by qdd1234** [comment]
> ls -l /home/kkk/coco/train2017|grep

您好，好像没有返回结果，这是什么yaunyin原因呢。。。。
![image](https://user-images.githubusercontent.com/68497831/143375814-50103be4-fc9d-4976-916b-545ca4773bd7.png)

**Comment by MendelXu** [comment]
可能你的数据集没下完全？

**Comment by qdd1234** [comment]
> 这个，，，，，，我重新下载一下吧，可否方便您看一下您下载的训练集数据量是不是116172张？如果不是的话那应该就是我下载错了

这个，，，，，，我重新下载一下吧，可否方便您看一下您下载的训练集数据量是不是116172张？如果不是的话那应该就是我下载错了

**Comment by MendelXu** [comment]
应该是118287

**Comment by qdd1234** [comment]
> 应该是118287

好的，我重新下载数据集，非常感谢，这个问题困扰了我很久了，因为我一直用的是您官方代码，应该是没有问题的才对

**Comment by qdd1234** [comment]
您好，还有一个问题想问一下，您程序中有一个命令好像是wanb这个库，运行的时候需要选择3个选项，我想问一下怎么关闭这个命令？

**Comment by MendelXu** [comment]
"We use wandb for visualization, if you don't want to use it, just comment line 273-284 in configs/soft_teacher/base.py."

**Comment by qdd1234** [comment]
> "We use wandb for visualization, if you don't want to use it, just comment line 273-284 in configs/soft_teacher/base.py."

在您的文章中，您提及所有检测模型都随机初始化，而其他模型例如Unbiased-teacher，都有一个先在已有标签上训练一下，这样话初期伪标签生成质量会高一些，但是您这个模型随机初始化那么训练初期的伪标签质量如何保证？谢谢~

**Comment by MendelXu** [comment]
训练初期都过滤掉了，没有伪标签

**Comment by qdd1234** [comment]
> 训练初期都过滤掉了，没有伪标签

好的，我再细看一下论文，谢谢答复~
