### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by qdd1234** [microsoft/SoftTeacher#122]
您好，您代码中有些代码我没怎么理解，向您请教一下
![image](https://user-images.githubusercontent.com/68497831/143671561-851dfee6-0cd1-40f0-abe0-993e80a2bcc2.png)
图中，这个函数具体是干嘛的，对应论文里面那个部分的功能？谢谢！

还有，您论文中的soft-teacher中的无监督那个部分的分类损失函数公式，在代码中哪一行体现，我找到了unsup_cls这个函数，但是具体能够体现公式的这个代码我没看懂，可以帮忙指明一下吗，谢谢
![image](https://user-images.githubusercontent.com/68497831/143671638-b8963c72-c2ae-45e4-8b8b-9c70ac7e67d6.png)

**Comment by MendelXu** [comment]
1）这个函数其实是roi head里面对poposal进行采样的函数（正样本），是直接从roi head里面copy过来的，跟整体方法无关；
2）参考https://github.com/microsoft/SoftTeacher/blob/97064fbcce1ab87b40977544ba7a9c488274d66f/ssod/models/soft_teacher.py#L236

**Comment by qdd1234** [comment]
那个wandb库，在训练时候需要确定是否 可视化，但是我是放在linux后台运行，这样怎么写一个脚本训练文件使得可以在终端可以自动选择是否可视化？我将config中wandb注释掉会报错，好像不能注释我也不知道什么原因，可以教一下怎么写一个linux终端脚本自动选择吗，谢谢

**Comment by MendelXu** [comment]
最新的代码应该是可以注释掉的，你可以试试。
