### ISSUE TITLE
paper issue

### ISSUE THREAD

**Issue by qdd1234** [microsoft/SoftTeacher#125]
您好，对于你的paper，我有几个问题想和您讨论一下：
（1）Soft-teacher中是否考虑到前景与背景不平衡问题？
（2）在3.2小节 Soft-teacher小节中，如下图，既然我设定一个较高的阈值，那么模型很确信这个预测的就是前景而不是背景，怎么会导致一个real annotation被看成背景呢，那这问题是不是可能是由于这个real annotation在数据集中数量较少导致的？
![QQ图片20211201145213](https://user-images.githubusercontent.com/68497831/144186161-1462589b-120e-430c-81ab-a48cca4c8e39.png)

**Comment by MendelXu** [comment]
(1)并没有考虑，这个不能算semi特有的问题,  之前有很多处理这个的工作，你可以参考。
(2） 这里的real annotation是指图片中真实存在的物体，比如有三个物体，设置比较高的阈值的时候可能只找出了一个物体。

**Comment by qdd1234** [comment]
还有一个小问题，就是Soft-teacher里面，预测下图中的r值是不是暂时只能使用两阶段模型，单阶段的目标检测模型因为没有ROI部分
![image](https://user-images.githubusercontent.com/68497831/144197028-5893ea75-3a5b-4000-aa2c-c82d384aa6d6.png)

**Comment by MendelXu** [comment]
是的
