### ISSUE TITLE
Instance segmentation results in partially-labeled setting

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/SoftTeacher#127]
Hi! We're looking to potentially build upon SoftTeacher framework in the partially-labeled setting.

The paper provides results of instance segmentation only in the fully-labeled (COCO 100%) setup. Have you tried to run in partially-labeled setup? (COCO 1% / 5% / 10%) This baseline would be very interesting!

Thank you!

**Comment by MendelXu** [comment]
No. We didn't try it. But I think it is a good idea to do this.

**Comment by vadimkantorov** [comment]
I'll let you know if we get good results with this. I saw in other issues that people have asked earlier about reproducing segmentation results. Are the segmentation configs now available? Thanks!

**Comment by MendelXu** [comment]
No. It is not available now.

**Comment by vadimkantorov** [comment]
Sigh. Okay, thanks, looking forward to them to make a fair comparison!
