### ISSUE TITLE
Detecting objects using a pre-trained SoftTeacher

### ISSUE THREAD

**Issue by diogofd8** [microsoft/SoftTeacher#13]
Could you please clarify the process of trying out this detector with our own images? I don't want to retrain, just to download your best weights and try it out. Is it possible?

**Comment by MendelXu** [comment]
If I understand it correctly, you just want a script which accepts some image paths as input and outputs the detection results right?

**Comment by diogofd8** [comment]
Exactly!

**Comment by MendelXu** [comment]
@diogofd8 I add a script to do inference on custom images. Could you have a look and see whether it satisfies your needs?
