### ISSUE TITLE
try to implement it in yolov5, but bad performance

### ISSUE THREAD

**Issue by klykq111** [microsoft/SoftTeacher#131]
作者你好，我正在尝试将当前算法实现到yolov5上，已经完成了一个版本，但是现在效果很差。主要原因是如果对无标签的数据没有预测出伪标签的话，只会有unsup_obj_loss，而unsup_box_loss和unsup_cls_loss都没有，导致目前模型训练会倾向于将无标签的图片都预测作为背景，不产生伪标签。这样的话模型在测试集上的recall和map都很低。你能给我任何建议吗？非常感谢。

**Comment by MendelXu** [comment]
我举得你可能要先看看正常情况下预测结果的分布，看看是什么原因导致没有生成伪标签。

**Comment by Him-wen** [comment]
@klykq111 @MendelXu How to implement this module in yolov5?

**Comment by klykq111** [comment]
@MendelXu box jittering部分，在faster rcnn中，是将抖动后的框输入回rcnn中进行回归，将这些回归框的方差作为可靠性度量。但是在one-stage网络中，没有类似的rcnn部分进行回归。这一部分你有什么想法吗？
