### ISSUE TITLE
What is the effect of using no augmentation instead of weak augmentation for teacher?

### ISSUE THREAD

**Issue by lhphanto** [microsoft/SoftTeacher#135]
Hi,

Just wonder if it is ok to have no data augmentation for teacher model (instead of weak augmentation)?

Thanks!

**Comment by Jack-Hu-2001** [comment]
Well, I guess very weak data augmentation like random flip is used as regularization and is essential for the generalization of model, theoretically. Maybe mAP will drop a little, you could try this as a practice. Actually, I don't think this setting change makes much sense for this situation.

**Comment by lhphanto** [comment]
Thanks, Jack!
So I thought the reason why we have different augmentation for teacher and
student is to do some kind of consistency matching? If so,  I was wondering
why we can't do all the augmentation in the student. And leave teacher
alone, which is used for generating labels, and is like a eval/inference
job. And for eval jobs, we don't necessarily need data augmentation, I
think?

**Comment by Jack-Hu-2001** [comment]
Just like augment test, when testing, weak augment improves mAP. Same reason here, weak augment improves the quality of psuedo labels, I guess.

**Comment by Jack-Hu-2001** [comment]
Like, here. https://machinelearningmastery.com/how-to-use-test-time-augmentation-to-improve-model-performance-for-image-classification/
