### ISSUE TITLE
Box Jittering in a Single-Stage Coupled-Head Detection Scenario

### ISSUE THREAD

**Issue by rocketsfallonrocketfalls** [microsoft/SoftTeacher#139]
Hey, 

Thanks a lot for the great paper and repo.

I was wondering how (or if ever) that box jittering could be implemented in a single-stage detector with a coupled detection head (i.e. YOLO head) where there is no built-in module for box refinement for extracted regions of interest. 

Any intuitions?

**Comment by MendelXu** [comment]
I think it is hard to do this as discussed in the previous issue. Currently, I have no idea how to implement such operations in YOLO. Maybe you can refer to other methods.

**Comment by rocketsfallonrocketfalls** [comment]
Thanks for the reply.

**Comment by rocketsfallonrocketfalls** [comment]
@MendelXu, in the paper it is said that the presented end-to-end pipeline with the Soft Teacher approach can be implemented using Single-Stage Object Detectors as well. Could you elaborate what was the intuition behind this statement? Is there anything special with the YOLO head?

**Comment by MendelXu** [comment]
For a single-stage detector, you have to input several augmented images and count the variance between them. However, I think it will be slow and not applicable.
