### ISSUE TITLE
Swin transformer based codes and configs

### ISSUE THREAD

**Issue by amobiny** [microsoft/SoftTeacher#14]
Hi there,
thanks for the nice work and congrats on getting accepted at ICCV2021.
I was wondering if you are planning to release the swin-transformer codes? especially for the instance segmentation model.

Best,

**Comment by stupidZZ** [comment]
At present, we have no plans to release the **Swin-L+HTC++** model/config before the official release of the relevant code/model/configs by the Swin Project.

For other Swin-based models, such as Swin+Mask R-CNN, we are considering releasing the code/model/configs, after all other R50/R101 models are released, and it also will take time to ensure everything is reproducible.
