### ISSUE TITLE
Questions about code.

### ISSUE THREAD

**Issue by UT-Mao** [microsoft/SoftTeacher#141]
1. 请问ssod/models/soft_teacher.py中定义的soft teacher的实例化是在哪里进行的？
2. 请问config中的semi_wrapper是在哪里发挥作用的？

**Comment by MendelXu** [comment]
1. 实例化的代码在mmdetection里面
2. 之所以这么写是为了方便直接引用 supervised model。其实等同于`model=dict(type='SoftTeacher',student=dict(type='FasterRCNN'...))`

**Comment by UT-Mao** [comment]
感谢您的回复，
mmdetection基于config文件实例化，因为调试您的code的时候看到在tools/train.py的文件中构建的模型type还是Faster R-CNN，我想知道的构建SoftTeacher这一步骤发生在哪里。（不是指具体的build_from_config方法，而是在哪里接受了config中描述的要构筑SoftTeacher模型的信息），请问相关的代码具体是在哪几行。
或者说，像您说的第二点，等同于 `model=dict(type='SoftTeacher'...)` 这一部分，是如何做到‘等同于’的。我希望我有表达清楚我的问题，因为想基于您的代码进行进一步的Research，期待您的答复。

**Comment by MendelXu** [comment]
在这里~https://github.com/microsoft/SoftTeacher/blob/bef9a256e5c920723280146fc66b82629b3ee9d4/ssod/utils/patch.py#L76

**Comment by UT-Mao** [comment]
感谢！
