### ISSUE TITLE
SoftTeacher error for Mask RCNN 

### ISSUE THREAD

**Issue by gouthamkallempudi** [microsoft/SoftTeacher#146]
Thanks for the great Code!!

I am trying to use mask RCNN capabilities with SoftTeacher.
I changed baseline config to support MaskRCNN on my dataset and it works fine, however when I use it for softteacher config the code is unable to load mask details.

In the train_pipeline and other pipelines I have added with_mask = True and also gt_maks in the collect area. However I am getting the below error.

   

> File "/opt/conda/lib/python3.8/site-packages/ssod/apis/train.py", line 206, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
>     iter_runner(iter_loaders[i], **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
>     outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
>     output = self.module.train_step(*inputs[0], **kwargs[0])
>   File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 238, in train_step
>     losses = self(**data)
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
>     output = old_func(*new_args, **new_kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 172, in forward
>     return self.forward_train(img, img_metas, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/ssod/models/soft_teacher.py", line 49, in forward_train
>     self.foward_unsup_train(
>   File "/opt/conda/lib/python3.8/site-packages/ssod/models/soft_teacher.py", line 77, in foward_unsup_train
>     return self.compute_pseudo_label_loss(student_info, teacher_info)
>   File "/opt/conda/lib/python3.8/site-packages/ssod/models/soft_teacher.py", line 124, in compute_pseudo_label_loss
>     self.unsup_rcnn_reg_loss(
>   File "/opt/conda/lib/python3.8/site-packages/ssod/models/soft_teacher.py", line 280, in unsup_rcnn_reg_loss
>     loss_bbox = self.student.roi_head.forward_train(
>   File "/opt/conda/lib/python3.8/site-packages/mmdet/models/roi_heads/standard_roi_head.py", line 110, in forward_train
>     mask_results = self._mask_forward_train(x, sampling_results,
>   File "/opt/conda/lib/python3.8/site-packages/mmdet/models/roi_heads/standard_roi_head.py", line 171, in _mask_forward_train
>     mask_targets = self.mask_head.get_targets(sampling_results, gt_masks,
>   File "/opt/conda/lib/python3.8/site-packages/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 143, in get_targets
>     mask_targets = mask_target(pos_proposals, pos_assigned_gt_inds,
>   File "/opt/conda/lib/python3.8/site-packages/mmdet/core/mask/mask_target.py", line 59, in mask_target
>     mask_targets = map(mask_target_single, pos_proposals_list,
> TypeError: 'NoneType' object is not iterable 

Below is my compiled config file :              
               
  
[compiled_config.txt](https://github.com/microsoft/SoftTeacher/files/7835092/compiled_config.txt)
        

Below is how my config file looks like

[base.txt](https://github.com/microsoft/SoftTeacher/files/7835051/base.txt)

**Comment by MendelXu** [comment]
You may refer to this:
https://github.com/MendelXu/SoftTeacher/blob/main/ssod/models/mask_soft_teacher.py
(As I have not debugged it carefully, I will not push it to this repo recently. You'd better read it to avoid possible bugs.)

**Comment by gouthamkallempudi** [comment]
Thank you for your quick response and mask soft teacher code!!
