### ISSUE TITLE
For removing wandb

### ISSUE THREAD

**Issue by leeeeeng** [microsoft/SoftTeacher#15]
Thanks for the great job!

I just want to remove the wandb, but removing line 276-289 of "base.py" seems strange. Does it mean that I should remove all the "log_config" part?

the line 276-289 in base.py:
https://github.com/microsoft/SoftTeacher/blob/9055647b7461c2b3487ec438fce7b842b1f76ad9/configs/soft_teacher/base.py#L276-L286
the lines stop at 286. I am not sure about the specific modification.

Best wishes.

**Comment by leeeeeng** [comment]
https://github.com/microsoft/SoftTeacher/blob/9055647b7461c2b3487ec438fce7b842b1f76ad9/configs/soft_teacher/base.py#L273-L284
I think line 273-284 could be the correct lines, right?

**Comment by MendelXu** [comment]
Yes, you are right. The README is out of date. I will fix it soon. Thank you

**Comment by MendelXu** [comment]
The tutorial is fixed now. Thanks for your help.
