### ISSUE TITLE
instances_unlabeled2017.json don't exists!

### ISSUE THREAD

**Issue by qq1243196045** [microsoft/SoftTeacher#151]
I have a custom dataset, and I have labeled a part of the data, the unlabeled ones have no labels, but in the config, unsup needs annfile, why does the unlabeled dataset need labels? what should I do?

**Comment by rocketsfallonrocketfalls** [comment]
Hey @qq1243196045, 

I have the exact issue and I was wondering if you were able to solve the problem. If so, do you mind share your solution? 

Thanks

**Comment by HeuristicLU** [comment]
DO you know how to gen unlabeled.json ? i use my custom dataset, thanks

**Comment by mary-0830** [comment]
请问你们解决了这个问题么？怎么解决的呢？谢谢！ @qq1243196045 @rocketsfallonrocketfalls @HeuristicLU
