### ISSUE TITLE
softteacher的项目运行的时候需要无标签数据的annotations文件，但是都说了是无标签数据了，哪里来的annotations呢。。。

### ISSUE THREAD

**Issue by qq1243196045** [microsoft/SoftTeacher#152]
softteacher的项目运行的时候需要无标签数据的annotations文件，但是都说了是无标签数据了，哪里来的annotations呢。。。

**Comment by MendelXu** [comment]
这个annotation文件只是用来存文件的图片id，图片路径这些信息的

**Comment by qq1243196045** [comment]
> 

我应该怎么获取这个文件呢

**Comment by qq1243196045** [comment]
> 这个annotation文件只是用来存文件的图片id，图片路径这些信息的

我应该怎么获取这个文件呢

**Comment by MendelXu** [comment]
写个脚本，按照正常生成coco annotation的格式就可以生成,https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_dataset.md

**Comment by qq1243196045** [comment]
> 写个脚本，按照正常生成coco annotation的格式就可以生成,https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_dataset.md
形如以下：
'images': [
    {
        'file_name': '001268.jpg',
        'height': 427,
        'width': 640,
        'id': 1268
    },
   
],

'annotations': [],

'categories': [ ]

这样的就可以了是吗

**Comment by qq1243196045** [comment]
> 写个脚本，按照正常生成coco annotation的格式就可以生成,https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/customize_dataset.md

形如以下：
'images': [
{
'file_name': '001268.jpg',
'height': 427,
'width': 640,
'id': 1268
},

],

'annotations': [],

'categories': [ ]

这样的就可以了是吗

**Comment by MendelXu** [comment]
对的

**Comment by qq1243196045** [comment]
> 对的

明白了，非常感谢！
