### ISSUE TITLE
Mask predictions

### ISSUE THREAD

**Issue by Abdullah955** [microsoft/SoftTeacher#154]
I've installed and tested the model on Box prediction and it works fine, when i tried to switch to masks referring to this page
https://github.com/MendelXu/SoftTeacher/blob/main/ssod/models/mask_soft_teacher.py

where can i switch from the soft_teacher.py to mask_soft_teacher.py ?

**Comment by MendelXu** [comment]
You can refer to https://github.com/microsoft/SoftTeacher/issues/146 to modify your config (change `semi_wrapper.type` to `MaskSoftTeacher`)and add `from .mask_soft_teacher import MaskSoftTeacher` in `ssod/models/__init__.py`

**Comment by Abdullah955** [comment]
I'm facing 
`ArrtibuteError: 'StandardRoIHead' object has no attribute 'mask_head'`
do you think it's a version problem ?

**Comment by MendelXu** [comment]
No. Please refer to #146.
![image](https://user-images.githubusercontent.com/44802022/150755065-a57035a7-1dc8-4655-984f-784d46170517.png)

**Comment by Abdullah955** [comment]
I've already edited the base file still have same problems as this issue 

https://github.com/microsoft/SoftTeacher/issues/146
TypeError: 'NoneType' object is not iterable

and i've added the same roi_head configurations you mentioned.

**Comment by MendelXu** [comment]
OK. Thanks for your reply. I will post a correct config file here tonight.

**Comment by Abdullah955** [comment]
this should replace the base.py ?

**Comment by Abdullah955** [comment]
it worked! Thank you for great support
