### ISSUE TITLE
Formal defintion of G_cls, G_reg, l_cls, l_reg

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/SoftTeacher#155]
Hello @MendelXu!

The paper mentions that G_cls is produced from teacher model by foreground filtering, G_reg is produced from teacher model by box variance filtering; unfortunately the paper doesn't mention the definition of `l_cls` and `l_reg`. `l_cls(student_candidate_box, teacher_pseudo_boxes)` and `l_reg(student_candidate_box, teacher_pseudo_boxes)` still needs to do label assignment. How is this assignment performed? What losses are used?

The paper mentions: `Another important benefit of this end-to-end framework is that it allows for greater leverage of the teacher model to guide the training of the student model, rather than just providing “some generated pseudo boxes with hard category labels” as in previous approaches [27, 36]. A soft teacher approach is proposed to implement this insight. In this approach, the teacher model is used to directly assess all the box candidates that are generated by the student model, `**`rather than providing “pseudo boxes” to assign category labels and regression vectors to these student-generated box candidates`**.

It seems that in SoftTeacher, pseudo boxes with hard labels (G_cls, G_reg) are still generated and that some standard IoU-based target-box matching / assignment (l_cls, l_reg) is used. If it's not the case, could you please bring some clarifications?

It's possible to recover this information from the code, but some formal definitions could help reading the code as well.

Thank you!

**Comment by vadimkantorov** [comment]
Thank you for your clarification about the losses!

A few questions about filtering of student and teacher boxes:
- is the same set of student (after filtering) boxes used for both classification and regression? 
- is the foregound score used for student box filtering also "defined as the maximum probability of all non-background categories"?
- Is the same foreground score threshold used for student box filtering and for teacher pseudo-box filtering?
- Are the foreground score threshold used for teacher box filtering different for G_cls and G_reg? Is NMS used for producing G_reg?

Thanks!

**Comment by MendelXu** [comment]
I am not sure what your question is. What are the student boxes after filtering?

**Comment by vadimkantorov** [comment]
My question is hwo:
- student boxes are filtered for classification: {b^fg_i}, {b^bg_i} (eq. 4) 
- student boxes are filtered for regression: I^i_u (eq. 11)
- teacher boxes are filtered for classification: `G_cls` (eq. 4)
- teacher boxes are filtered for regression: `G_reg` (eq.11 )

Thanks!

**Comment by MendelXu** [comment]
For the student, the boxes is not filtered. If you are familiar with the Faster RCNN, it is a candidate set sampled from a set of proposals following a fixed rule (Sampling positive samples and negatives with a sampling ratio).

**Comment by vadimkantorov** [comment]
I thought that at student boxes are first filtered using `prob_score > 0.9` (before any matching)

`In practice, we find that using a higher threshold on foreground score to filter out most of the student-generated box candidates with low-confidence can achieve better results than using a lower threshold. As shown in Table. 9, the best performance is achieved when the threshold is set to 0.9`

**Comment by MendelXu** [comment]
No. In the context of this sentence, there is no teacher model and only a student model trained with labeled data in a supervised manner.

**Comment by vadimkantorov** [comment]
Hmm, okay. To rephrase, how are these sets of student-generated boxes are defined: `{b^fg_i}` and `{b^bg_i}`? Thanks!

**Comment by MendelXu** [comment]
The student-generated boxes are split into fg and bg by their ious with the ground truth. (For labeled data, the ground truth is the annotations. For unlabeled data, the ground truth is the pseudo boxes.) The detail about how to assign each sample to the ground truth and the background and what is the iou threshold is described in the paper of  Faster RCNN.

**Comment by vadimkantorov** [comment]
In eq. 4 unsupervised `L_u^cls` is computed, so there is no ground truth, only pseudo ground truth. Do you mean that student-generated boxes are split into bg / fg by their ious with pseudo ground truth, right?

**Comment by MendelXu** [comment]
> I see, so standard Faster RCNN bg/fg IoU-based assignment is used. Indeed, phrasing `filter out most of the student-generated box` is quite confusing :( I was also confused by this phrasing and the fact that UnbiasedTeacher [does do](https://github.com/facebookresearch/unbiased-teacher/blob/main/ubteacher/engine/trainer.py#L537) student box filtering:

Yes. It seems a little confusing, maybe we should rewrite it...

**Comment by MendelXu** [comment]
> In eq. 4 unsupervised `L_u^cls` is computed, so there is no ground truth, only pseudo ground truth. Do you mean that student-generated boxes are split into bg / fg by their ious with pseudo ground truth, right?

Yes.
