### ISSUE TITLE
How to train and test on custom dataset?

### ISSUE THREAD

**Issue by purbayankar** [microsoft/SoftTeacher#16]
Thank you very much for the great work and congratulations on getting accepted at ICCV2021. Can you please provide description on Readme regarding training and testing with this framework on custom dataset?

**Comment by MendelXu** [comment]
Thanks for your advice. We will add this part ASAP.

**Comment by MendelXu** [comment]
To train and test on the custom dataset, you can convert it to coco format and update the file path in the config file. Details about it can be found in https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_dataset.md.

**Comment by Jack-Hu-2001** [comment]
Yes, but I guess some hyperameters should be changed if I use a dataset with different nums of images and so on. I'm reading the source code and try to figure it out. If you have time, please update a tutorial about that if possible. Then I could check if what I've changed is corrrespondet to what I need. Thanks!
