### ISSUE TITLE
ModuleNotFoundError: No module named 'ssod'

### ISSUE THREAD

**Issue by yuan738** [microsoft/SoftTeacher#185]
when I do this:
`python demo/image_demo.py tmp/*.jpg configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py work_dirs/iter_720000.pth --output work_dirs/`

the error:
```
Traceback (most recent call last):
  File "demo/image_demo.py", line 11, in <module>
    from ssod.apis.inference import init_detector, save_result
ModuleNotFoundError: No module named 'ssod'
```

**Comment by herfootsosmell** [comment]
I also encountered this problem， have you solved it?

**Comment by herfootsosmell** [comment]
I also encountered this problem， have you solved it?

**Comment by yuan738** [comment]
I downloaded mmdetection from github, changed the path of the coco dataset, and then there was no such error. 
I guess there should be something that isn't set right. 
I run the training code without error but I still have this error when I run inference.

**Comment by herfootsosmell** [comment]
OK，thanks for you!  you can try to set the pythonpath, export PYTHONPATH=$PYTHONPATH:/your ssod path/.

**Comment by yuan738** [comment]
thank you! I will try it.

**Comment by alaa-shubbak** [comment]
i faced same issue , and i don't know how to solve it. 
where shall i change the python path? 
by the way , i am running the codes in colab
