### ISSUE TITLE
Iterations in the logging

### ISSUE THREAD

**Issue by chunfuchen** [microsoft/SoftTeacher#20]
Thanks for sharing the codes. I have a question about the logging for evaluation.

When training a supervised baseline with 1% data (`fast_rcnn_r50_caffe_fpn_coco_partial_180k.py`), the evaluation is happened every 4000 iterations based on the configuration. However, in the logs, the iter idx is always `625`

```
{"mode": "train", "epoch": 28, "iter": 625, "lr": 0.01, "memory": 1985, "bbox_mAP": 0.083, "bbox_mAP_50": 0.209, "bbox_mAP_75": 0.045, "bbox_mAP_s": 0.036, "bbox_mAP_m": 0.094, "bbox_mAP_l": 0.11, "bbox_mAP_copypaste": "0.083 0.209 0.045 0.036 0.094 0.110", "data_time": 0.16451, "loss_rpn_cls": 0.04722, "loss_rpn_bbox": 0.06773, "loss_cls": 0.26717, "acc": 91.50293, "loss_bbox": 0.33872, "loss": 0.72084, "time": 0.32041}
```

Do you mind pointing me that where I should fix this? Thanks.

**Comment by MendelXu** [comment]
I have observed similar behavior. But as it doesn't affect the log on wandb, so I didn't try to solve it... I will have a look tomorrow. If there is any solution, I will post here.

**Comment by chunfuchen** [comment]
Thanks for your prompt reply! looking forward to the solution.

**Comment by MendelXu** [comment]
Hi, the problem should be fixed now. May you have a try?
