### ISSUE TITLE
ModuleNotFoundError: No module named 'ssod'

### ISSUE THREAD

**Issue by Banks1y** [microsoft/SoftTeacher#236]
Traceback (most recent call last):
  File "tools/train.py", line 18, in <module>
    from ssod.apis import get_root_logger, set_random_seed, train_detector
ModuleNotFoundError: No module named 'ssod'
Traceback (most recent call last):
  File "tools/train.py", line 18, in <module>
    from ssod.apis import get_root_logger, set_random_seed, train_detector
ModuleNotFoundError: No module named 'ssod'

**Comment by anhTuan24** [comment]
Hello, I have encountered the same problem. How did you solve it ? @Banks1y
