### ISSUE TITLE
Some questions about Soft-Teacher method 

### ISSUE THREAD

**Issue by songbae** [microsoft/SoftTeacher#24]
HI,i'm trying to implement this training method with out mmdetection  and i just want to train with my faster_rcnn code 
and i have read the paper but didn't clearly understand all the methods... i need some help 

Q1: When unsupervised learning , is the image already transformed by weak and hard augmentation?  i mean transformed images are the inputs of student and teacher model?

Q2: If they are already transformed , the bbox coordinates will be different with weak auged img and hard auged img if some kind of flip or rotate augmentation is applied. Then how to calculate the loss ?

Q3: And I have no idea what is in the "transform_matrix" in img_meta. what is in to the transform_matrix?

**Comment by MendelXu** [comment]
Yes, the inputs to both models are transformed with different augmentations. To calculate the loss between the student and teacher model, we have to map the coordinates to the same space. We use the `transform_matrix` to record the augmentation information. And then we are able to align inputs auged with different augmentations with the matrix.

**Comment by songbae** [comment]
> Yes, the inputs to both models are transformed with different augmentations. To calculate the loss between the student and teacher model, we have to map the coordinates to the same space. We use the `transform_matrix` to record the augmentation information. And then we are able to align inputs auged with different augmentations with the matrix.

thank you for reply , so you mean transform_matrix save the information of coordinates transformed  right?

**Comment by cnmckee** [comment]
I have another question- can't seem to find it in the paper. At inference time, is the teacher model or student model used for inference? Thanks.

**Comment by MendelXu** [comment]
@cnmckee In our paper and provided code, we use the student model for inference. However, in some cases, the teacher performs somewhat better than the student. So just for advice, you can try them both to see which is better.

**Comment by cnmckee** [comment]
> @cnmckee In our paper and provided code, we use the student model for inference. However, in some cases, the teacher performs somewhat better than the student. So just for advice, you can try them both to see which is better.

Makes sense- thanks for the speedy reply!
