### ISSUE TITLE
how to prepare dataset？

### ISSUE THREAD

**Issue by ljjcoder** [microsoft/SoftTeacher#25]
Thanks for your excellent work.  When I was preparing the data, I encountered a problem.
![1631937551(1)](https://user-images.githubusercontent.com/40750189/133871915-8e4d8d53-27e3-4f94-b7f8-772a4df308ec.jpg)
I downloaded the coco data set according to the instructions of STAC（https://github.com/google-research/ssl_detection）
But file image_info_unlabeled2017.json is missing when running your code（bash tools/dataset/prepare_coco_data.sh conduct）.
Can you help me fixed it?

**Comment by MendelXu** [comment]
This file can be downloaded from http://images.cocodataset.org/annotations/image_info_unlabeled2017.zip. I will update the tutorial to make it clear:sweat_smile:.

**Comment by ljjcoder** [comment]
@MendelXu Thanks for your reply. I fixed the problem. However, I ran into another problem.
![1632142209(1)](https://user-images.githubusercontent.com/40750189/134005085-a47b4a13-76dd-4edb-8a50-19dcf6a95d74.png)
can you help me？

**Comment by Jack-Hu-2001** [comment]
I wonder if parameters like 'epoch_length' and so on shold be changed if I use another dataset in coco format instead of coco.Tanks for your help!

**Comment by Jack-Hu-2001** [comment]
Thanks! I understand it now!

**Comment by Jack-Hu-2001** [comment]
Yeah, I solved the bug based on your suggestion! Thanks a lot!
