### ISSUE TITLE
Model training stops after validation after 4000 iterations

### ISSUE THREAD

**Issue by purbayankar** [microsoft/SoftTeacher#27]
After training for 4000 iterations the validation happens and after that the training stops throwing the following error:
```
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         tools/train.py FAILED         
=======================================
Root Cause:
[0]:
  time: 2021-09-22_05:54:53
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 2210236)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************
```
I am training with  2 gpus. Do you have any insight why this error is being thrown?

**Comment by MendelXu** [comment]
There lacks enough error information. I have no idea what the error is. Could you post the entire log here?

**Comment by leeeeeng** [comment]
I met this problem and solved it by installing mmcv=1.3.9 as the information in readme document. The problem happened when the version of mmcv is 1.3.12.

I can't find the exact problem, but using a lower version of mmcv really works for me.

**Comment by MendelXu** [comment]
I find some code in the new commit causes the problem But have no idea how to solve it properly. So I will revert to the old version...

**Comment by purbayankar** [comment]
Thank you very much @leeeeeng and @MendelXu. I got the error resolved following your suggestions. As I am currently using 2 gpus it shows 3 days for complete training. Can you please tell me in which folder model weights will be saved after training is completed?

**Comment by MendelXu** [comment]
By default, the weights are stored in `work_dirs/{CFG_NAME}{PERCENT}/{FOLD}`. If you are running the code with option `--work-dir {WORK_DIR}`, the weights are stored in `{WORK_DIR}`. By the way, as you are using 2 GPU, have you tried to adjust the learning rate (for example, reduce it to 1/4 of the original one)? The default learning rate may be too large for a smaller batch size.

**Comment by purbayankar** [comment]
@MendelXu thank you very much for the prompt reply. In the ```work_dirs/{CFG_NAME}{PERCENT}/{FOLD}``` folder I can only see ```.log``` and ```.log.json``` files.But I can't see any ```.pth``` file. Does the weights get saved after the complete 180k iterations are completed? And thank you very much for your suggestion. I am using a smaller learning rate as my batch size is small.

**Comment by MendelXu** [comment]
No. The weight is stored every 4000 iterations. https://github.com/microsoft/SoftTeacher/blob/863d90a3aa98615be3d156e7d305a22c2a5075f5/configs/soft_teacher/base.py#L265
You can change the `interval` to a smaller number like 50 to see whether there is still no model saved.

**Comment by purbayankar** [comment]
@MendelXu Thank you very much. The issue  is solved.

**Comment by purbayankar** [comment]
I am encountering another issue. Whenever I am trying to train using full labelled data setting using ```bash tools/dist_train.sh configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py 2```, I am getting the following error message:
```FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_unlabeled2017.json'```. But I downloaded the dataset from the official website and I do not seem to find ```instances_unlabeled2017.json``` in the Downloads section.

**Comment by MendelXu** [comment]
@purbayankar  you can download it from http://images.cocodataset.org/annotations/image_info_unlabeled2017.zip and put the extracted json file in `coco/annotations/`. Then execute `bash tools/dataset/prepare_coco_data.sh conduct`.

**Comment by duany049** [comment]
> @purbayankar you can download it from http://images.cocodataset.org/annotations/image_info_unlabeled2017.zip and put the extracted json file in `coco/annotations/`. Then execute `bash tools/dataset/prepare_coco_data.sh conduct`.

If I train model on the full labeled data setting, is it necessary for me to execute `bash tools/dataset/prepare_coco_data.sh conduct`(the percent in prepare_coco_data.sh belongs to {1%, 5%, 10%}, no 100%, so I don't execuete prepare_coco_data.sh, before I train full labeled data.)

**Comment by purbayankar** [comment]
@duany049 I'm not sure whether it is necessary or not but as per instruction of @MendelXu executing ```bash tools/dataset/prepare_coco_data.sh conduct``` solves the issue for me.

**Comment by MendelXu** [comment]
@duany049 It is still necessary.

**Comment by duany049** [comment]
> @duany049 It is still necessary.

If I added more data, but don't execute `prepare_coco_data.sh`, it means that I still train model with old data which is mall ?

**Comment by MendelXu** [comment]
Sorry, but what is "I still train model with old data which is mall ?"

**Comment by duany049** [comment]
> Sorry, but what is "I still train model with old data which is mall ?"

Thank you for your reply.
I use A unlabeled dataset at the first, and executing `prepare_coco_data.sh`, then I use B unlabeled dataset, but not executing `prepare_coco_data.sh`, so I still use A unlabeled dataset now, right?

**Comment by MendelXu** [comment]
What the script does is just to 1) prepare data split for partial setting on COCO 2) Convert `image_info_unlabeled2017.json` to `instances_unlabeled2017.json`. So it makes no sense to run it while adding any other dataset.

**Comment by duany049** [comment]
> What the script does is just to 1) prepare data split for partial setting on COCO 2) Convert `image_info_unlabeled2017.json` to `instances_unlabeled2017.json`. So it makes no sense to run it while adding any other dataset.

Thank you for solving my question
