### ISSUE TITLE
Meaning of epoch length

### ISSUE THREAD

**Issue by andreasHan** [microsoft/SoftTeacher#29]
First of all thanks for the excellent work.
I am really wondering about the meaning of **epoch_length** for the DistributedGroupSemiBalanceSampler，and the default value is 7330, and it works when contructing the sample index.

Thanks for your reply.

**Comment by MendelXu** [comment]
When we started the project, the `mmdetection` didn't support `IterBasedRunner` and we had to run the experiment epoch by epoch. As a result, we have to make sure that all images are sampled at least once during one epoch. So we set the variable `epoch_length` to 7330( The number is the epoch length if you run a supervised model on the coco dataset with 16 Image/Batch). The number is not special and keep it large enough should be ok in most cases.
