### ISSUE TITLE
Specify GPU ids in bash command

### ISSUE THREAD

**Issue by Jack-Hu-2001** [microsoft/SoftTeacher#33]
As a little rookie in this area, I wonna ask a simple question which I've been confused with.
I see that in this train.py, I can't specify gpu ids if I use dist training bash command like "bash <config> <gpu_nums>".
And I also tried setting os.environment variable CUDA_VISIBLE_DEVICE=2,3 in tools/train.py and it also don't work.
In the help it showed during training process:
`Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potent
ially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.  `
I guess it's the way to solve this issue but I didn't know how.
It's often the case in the group-shared machine that GPU 0 and 1 is heavily used and I need to use 2 or 3, but I failed to specify that , which delays my plans. 
Sorry for bothering you with this question.Thanks so much for your help! And I guess this might be added into tutorial,too!
(-u-)

**Comment by Jack-Hu-2001** [comment]
"bash <config><gpu_nums>"，I wrongly typed that.

**Comment by MendelXu** [comment]
Have you tried `CUDA_VISIBLE_DEVICE=2,3 bash tools/dist_train.sh xx`? The training script `tools/train.py` is launched by the pytorch launcher.  So before your newly added code executes, the launcher has spawn 8 processes already. So instead of setting it in the python script, I would rather add it in the bash script or in the terminal by `export CUDA_VISIBLE_DEVICES=2,3`

**Comment by Jack-Hu-2001** [comment]
YEAH! It worked! Actually I have tried this method before, but I crashed the program as soon as I saw the same warning information I mentioned above. The gpu0,1 now is not the same as the ones used in previous command, they're actually what I needed. Sincerely thanks!

**Comment by Jack-Hu-2001** [comment]
And thanks for your great explanation, I got to understand why!
