### ISSUE TITLE
If use own unlabeled dataset to do unsupervised learning, what is input training instructions?(Because there's a <PERCENT_LABELED_DATA> option in training, how do I set this?)

### ISSUE THREAD

**Issue by wqzustc** [microsoft/SoftTeacher#38]

**Comment by MendelXu** [comment]
You can refer to this config [file](https://github.com/microsoft/SoftTeacher/blob/main/configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py). 

And change something in the config file like:
```python
data = dict(
    train=dict(
       sup=dict(
                     type="CocoDataset",
                    ann_file="YOUR_SUP_ANN_FILE",
                    img_prefix="YOUR_SUP_IMG_PREFIX", 
        )
        unsup=dict(
                    type="CocoDataset",
                    ann_file="YOUR_UNSUP_ANN_FILE",
                    img_prefix="YOUR_UNSUP_IMG_PREFIX", 
        )
    )
       ...
)
```

**Comment by wqzustc** [comment]
After that, as for command I use "bash tools/dist_train_partially.sh semi 2"or"bash tools/dist_train.sh configs/soft_teacher/xxxxx.py 2"?  If it's the first command the parameter "<PERCENT_LABELED_DATA> ",do I need to set it?

**Comment by MendelXu** [comment]
The latter command.

**Comment by wqzustc** [comment]
Thank you!
