### ISSUE TITLE
Mappings between labeled and unlabeled data

### ISSUE THREAD

**Issue by olivierlam97** [microsoft/SoftTeacher#40]
Hello,

First of all, thank you for the work on this very interesting project! 

I am combining multiple datasets for a project and would like to use SoftTeacher for object detection. 

My question is the following:

Do the annotation data for labeled data be consistent with the one for unlabeled data ? For example, in the labeled data, the category_id 0 correspond to rice, then should it be the case in the annotations file for unlabeled data? (same question for image_id and annotation_id)

Thank you in advance!

**Comment by MendelXu** [comment]
It is better to keep the categories list the same. However, the training should be ok if it is not as the categories list is not used in training. For image_id and annotation_id, there is no need to keep them consistent with the labeled data.

**Comment by olivierlam97** [comment]
Thank you!
