### ISSUE TITLE
Error in training 

### ISSUE THREAD

**Issue by luisfra19** [microsoft/SoftTeacher#42]
Error in full training:

tools/train.py FAILED         
=======================================
Root Cause:
[0]:
  time: 2021-10-04_17:02:18
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 921)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>

I am using only one GPU, get an error in full training with my own data converted to COCO. 

Firstly, I segmented the data with "bash tools/dataset/prepare_coco_data.sh conduct", then trained  with "bash tools/dist_train.sh configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py 1 "

I also trained as the readme file with the COCO data, and still obtain errors, in full or semi training.
It gets stuck in:
INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_mhoa0vu3/none_y1enyj09/attempt_0/0/error.json

**Comment by luisfra19** [comment]
Do you need more information or should I present it in a different way?

**Comment by MendelXu** [comment]
Could you update the full log here?

**Comment by luisfra19** [comment]
I should also add that I'm working with WSL.

**Comment by MendelXu** [comment]
It will be very slow, I think. Maybe you can use docker to run the job.
