### ISSUE TITLE
Is there a fixed IMG size or can I use any image size?

### ISSUE THREAD

**Issue by sarmientoj24** [microsoft/SoftTeacher#43]
Else, where do I edit the img size.

**Comment by Jack-Hu-2001** [comment]
In config file configs/Soft teacher/base.py
serach train_pipeline and test_pipeline
you'll see:
`type="RandResize", img_scale=[(1333, 400), (1333, 1200)]`
and you can modify it here.

**Comment by Jack-Hu-2001** [comment]
@sarmientoj24 choose your process train or test!

**Comment by sarmientoj24** [comment]
is it recommended to change the size for the detections or just let it be like this?

**Comment by sarmientoj24** [comment]
for both train and test, i mean. :)

**Comment by Jack-Hu-2001** [comment]
all the pictues will be resized so you can use image size as you need and resize it to the scale you need
this can provide best map in COCO dataset, I guess.You can simply change it to a number around your actual image size.
If the size is too small, map will drop.Too large, calculation cost will be too much and map won't increase aparently.

**Comment by Jack-Hu-2001** [comment]
then change the both train_pipeline and test_pipeline

**Comment by Jack-Hu-2001** [comment]
pay attention that there are three (1333,400) in this py and change them all!
Two are for train (one for student another for teacher) and one is for test!

**Comment by Jack-Hu-2001** [comment]
If there's anything wrong I 've said,please correct me.
@MendelXu

**Comment by sarmientoj24** [comment]
from what I know, COCO is about 640x480. I see.
what I thought is that `RandResize` randomly resizes it on either of the given sizes.
