### ISSUE TITLE
Feasable to train on fewer/single GPU?

### ISSUE THREAD

**Issue by Karol-G** [microsoft/SoftTeacher#55]
Hi,

in the paper it is stated that you used 8 GPUs for training. Some questions regarding that:

- Can you specify what kind of GPUs you used (name, amount of GPU memory)?
- How long did the training take with your 8 GPUs?
- Is it necessary to train with this many GPUs or would the training time with the same settings be otherwise way to long?

Best Karol

**Comment by MendelXu** [comment]
1) 8 Nvidia V100, each with 16 GB;
2) For 180k, about 1.5 days. For 720k or a longer schedule, a longer time is needed.
3) The simplest way is to keep the total batch size the same while changing GPU num and the training time will be longer.
