### ISSUE TITLE
Learning curve for Full Labeled Data experiment 

### ISSUE THREAD

**Issue by JasonChen75** [microsoft/SoftTeacher#59]
Hi, 

I found it is hard to squeeze the Full Labeled Data experiment into 8 2080_ti GPUs. Could you provide the training logs, including the mAP, training losses, and other metrics along with the training iterations? 

Thanks.

**Comment by MendelXu** [comment]
You can refer to https://drive.google.com/drive/folders/1XFabi22Rg2ZNePt51-_tJDiuk8pLABV6?usp=sharing. As our job was running on a preemptable service, it produces multiple log files for the single job, please read them by the timestamp.

**Comment by zen-star** [comment]
Hello, the log link is 404, please give another link~thx
