### ISSUE TITLE
loading weights issue

### ISSUE THREAD

**Issue by miraclebiu** [microsoft/SoftTeacher#6]
When I run the code, I can see logs:"unexpected key in source state_dict: conv1.bias, layer1.0.conv1.bias.......". all unexpected keys are bias, I don't know whether this will affect performance or not.

**Comment by MendelXu** [comment]
I can't reproduce this issue. Did you change the code or config file?

**Comment by miraclebiu** [comment]
> I can't reproduce this issue. Did you change the code or config file?
my log is like this, maybe you can saerch this in your log.
Pretrained weights is specified in the configuration file which I download from Internet and put it in the pretrain folder
![image](https://user-images.githubusercontent.com/16793970/133179666-416c4a35-7969-4809-84e9-2154fba37b81.png)

**Comment by MendelXu** [comment]
Could you post the full log and more information here? I can't find this line in my log. Are you using an old version of mmdetection?

**Comment by MendelXu** [comment]
I think a possible reason is that you have downloaded the wrong pre-trained weights. Note that all of our models are using Caffe style backbone. So if you want to download and load the weight manually, maybe you should download it from the following links:
```
For ResNet50:
https://download.openmmlab.com/pretrain/third_party/resnet50_caffe-788b5fa3.pth
For ResNet101:
https://download.openmmlab.com/pretrain/third_party/resnet101_caffe-3ad79236.pth
```

**Comment by miraclebiu** [comment]
> I think a possible reason is that you have downloaded the wrong pre-trained weights. Note that all of our models are using Caffe style backbone. So if you want to download and load the weight manually, maybe you should download it from the following links:
> 
> ```
> For ResNet50:
> https://download.openmmlab.com/pretrain/third_party/resnet50_caffe-788b5fa3.pth
> For ResNet101:
> https://download.openmmlab.com/pretrain/third_party/resnet101_caffe-3ad79236.pth
> ```
I use resnet50 for training and the file md5 value is 
3238aad43626654ec88021900df0c756, which is the same as file from the download link

**Comment by miraclebiu** [comment]
> Could you post the full log and more information here? I can't find this line in my log. Are you using an old version of mmdetection?

mmdetection is cloned from github

**Comment by MendelXu** [comment]
Sorry. I am still unable to reproduce your case. Could you share the config file?

**Comment by MendelXu** [comment]
Hi, you should download resnet50 model from https://download.openmmlab.com/pretrain/third_party/resnet50_msra-5891d200.pth. The ;ink posted in the official mmdetection repo is wrong

**Comment by miraclebiu** [comment]
> Hi, you should download resnet50 model from https://download.openmmlab.com/pretrain/third_party/resnet50_msra-5891d200.pth. The ;ink posted in the official mmdetection repo is wrong

Great!!
