### ISSUE TITLE
Question about EMA

### ISSUE THREAD

**Issue by songbae** [microsoft/SoftTeacher#64]
I don't understand where EMA updates happens

after update loss of sup+unsup, it   just returns loss in softteacher 

where does ema update happens?

**Comment by MendelXu** [comment]
Yes, if you want to adjust these parameters, maybe you can write an extension.

**Comment by lhphanto** [comment]
Sorry to came back on this old thread.

I see for EMA update, the momentum itself is dynamically decayed. 

This is a little bit different from for example https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage

Just wonder if dynamically decaying the momentum was found to be very helpful? Or it was relatively minor improvment?

Thanks!

**Comment by MendelXu** [comment]
No. The implementation to decay the momentum is not used in our experiments. It is just a option provided for the user.
