### ISSUE TITLE
question about box jittering

### ISSUE THREAD

**Issue by songbae** [microsoft/SoftTeacher#65]
after box jittering  10times you have a set of boxes of 10 jittered boxes and after refine if the variance is less than 0.02 you use the detected box as pseduo box  in repo .

Q1. you already have made 10 boxes and why not pick the best jittered box? i mean you know the variance and mean of the box coord , and i think it's better using the jittered box which is close to the mean of 10 jittered box.  

Q2. not using best jittered box is that it takes some computations? and training speed get lower?

**Comment by MendelXu** [comment]
Q1: Yes, you can use the mean value, we didn't use it in our experiments and we only used the variance.
Q2: I think it will not consume many computations compared to the whole pipeline.
