### ISSUE TITLE
I has a question about filter_invalid

### ISSUE THREAD

**Issue by leijie0106** [microsoft/SoftTeacher#66]
![image](https://user-images.githubusercontent.com/92840063/138026682-9044c6c6-775c-4a6b-96ef-a35ee485c102.png)
![image](https://user-images.githubusercontent.com/92840063/138026724-455d5656-6fc4-434d-84c3-38e7d34f0cb8.png)
thr is negative, so bbox jittering is not used, Am I misinterpreting this ?

**Comment by MendelXu** [comment]
I have checked the old version code and this version. And I think you are right. There is a bug in this bug in this version. It doesn't exist in the old version. I am not sure why I add this line to this version... I will rerun it and update the result.
![image](https://user-images.githubusercontent.com/44802022/138034060-7bd48fea-35e4-4a49-8a51-90be605f66bc.png)

**Comment by leijie0106** [comment]
thank you
