### ISSUE TITLE
Can clarify or correct the requirements.txt?

### ISSUE THREAD

**Issue by sarmientoj24** [microsoft/SoftTeacher#74]
I am currently having a hard time installing the libraries in `requirements.txt` and it seems different than the environment stated in the README file.

For example, I am getting
```
pip install mmdet==2.16.0+fe46ffe
ERROR: Could not find a version that satisfies the requirement mmdet==2.16.0+fe46ffe
ERROR: No matching distribution found for mmdet==2.16.0+fe46ffe
```

Also, the requirements state Pytorch 1.9.0 and mmcv but the ones in the requirements.txt are all not versioned so it will provide the latest ones. I cannot also install mmcv-full 1.3.9 as well since it does not exist in https://download.openmmlab.com/mmcv/dist/ for Pytorch 1.9 + CUDA 11.0.

**Comment by MendelXu** [comment]
For the `mmdetection`, you have to clone it from the official repo and install it manually. 
For the `mmcv-full`, you have to install it by 
`pip install mmcv-full==1.3.9 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
`
All those information can be found in the related git repo.
https://github.com/open-mmlab/mmdetection
https://github.com/open-mmlab/mmcv
