### ISSUE TITLE
assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}"

### ISSUE THREAD

**Issue by duany049** [microsoft/SoftTeacher#8]
When I use my custom data, raise error: "assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}""
then I print the length info,  =====len of indices is 29336 - offset: 0 - len self 58640

below is the detail error info, Please help me.

Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 193, in main
    meta=meta,
  File "/home/swap/project/SoftTeacher/ssod/apis/train.py", line 205, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in run
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in <listcomp>
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 23, in __init__
    self.iter_loader = iter(self._dataloader)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/swap/project/SoftTeacher/ssod/datasets/samplers/semi_sampler.py", line 186, in __iter__
    assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}"

**Comment by MendelXu** [comment]
> When I use my custom data, raise error: "assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}""
> then I print the length info, =====len of indices is 29336 - offset: 0 - len self 58640
> 
> below is the detail error info, Please help me.
> 
> Traceback (most recent call last):
> File "tools/train.py", line 198, in
> main()
> File "tools/train.py", line 193, in main
> meta=meta,
> File "/home/swap/project/SoftTeacher/ssod/apis/train.py", line 205, in train_detector
> runner.run(data_loaders, cfg.workflow)
> File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in run
> iter_loaders = [IterLoader(x) for x in data_loaders]
> File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in
> iter_loaders = [IterLoader(x) for x in data_loaders]
> File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 23, in **init**
> self.iter_loader = iter(self._dataloader)
> File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in **iter**
> return _MultiProcessingDataLoaderIter(self)
> File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 764, in **init**
> self._try_put_index()
> File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
> index = self._next_index()
> File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
> return next(self._sampler_iter) # may raise StopIteration
> File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in **iter**
> for idx in self.sampler:
> File "/home/swap/project/SoftTeacher/ssod/datasets/samplers/semi_sampler.py", line 186, in **iter**
> assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}"

Could you post more information like GPU numbers, dataset size? It will be helpful for us to debug it.

**Comment by duany049** [comment]
> > When I use my custom data, raise error: "assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}""
> > then I print the length info, =====len of indices is 29336 - offset: 0 - len self 58640
> > below is the detail error info, Please help me.
> > Traceback (most recent call last):
> > File "tools/train.py", line 198, in
> > main()
> > File "tools/train.py", line 193, in main
> > meta=meta,
> > File "/home/swap/project/SoftTeacher/ssod/apis/train.py", line 205, in train_detector
> > runner.run(data_loaders, cfg.workflow)
> > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in run
> > iter_loaders = [IterLoader(x) for x in data_loaders]
> > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in
> > iter_loaders = [IterLoader(x) for x in data_loaders]
> > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 23, in **init**
> > self.iter_loader = iter(self._dataloader)
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in **iter**
> > return _MultiProcessingDataLoaderIter(self)
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 764, in **init**
> > self._try_put_index()
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
> > index = self._next_index()
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
> > return next(self._sampler_iter) # may raise StopIteration
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in **iter**
> > for idx in self.sampler:
> > File "/home/swap/project/SoftTeacher/ssod/datasets/samplers/semi_sampler.py", line 186, in **iter**
> > assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}"
> 
> Could you post more information like GPU numbers, dataset size? It will be helpful for us to debug it.

Thank you for your attention.
Below is my information:
GPU:   GeForce RTX 3070,      CUDA:  cuda_11.2.r11.2/compiler.29558016_0,    Driver Version:    460.91.03,    Pytorch: 1.9
Dataset infomation: 
labeled train imgs: 1798,     labeled val imgs: 201,    unlabeled imgs:  7000

**Comment by duany049** [comment]
> > > When I use my custom data, raise error: "assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}""
> > > then I print the length info, =====len of indices is 29336 - offset: 0 - len self 58640
> > > below is the detail error info, Please help me.
> > > Traceback (most recent call last):
> > > File "tools/train.py", line 198, in
> > > main()
> > > File "tools/train.py", line 193, in main
> > > meta=meta,
> > > File "/home/swap/project/SoftTeacher/ssod/apis/train.py", line 205, in train_detector
> > > runner.run(data_loaders, cfg.workflow)
> > > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in run
> > > iter_loaders = [IterLoader(x) for x in data_loaders]
> > > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in
> > > iter_loaders = [IterLoader(x) for x in data_loaders]
> > > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 23, in **init**
> > > self.iter_loader = iter(self._dataloader)
> > > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in **iter**
> > > return _MultiProcessingDataLoaderIter(self)
> > > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 764, in **init**
> > > self._try_put_index()
> > > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
> > > index = self._next_index()
> > > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
> > > return next(self._sampler_iter) # may raise StopIteration
> > > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in **iter**
> > > for idx in self.sampler:
> > > File "/home/swap/project/SoftTeacher/ssod/datasets/samplers/semi_sampler.py", line 186, in **iter**
> > > assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}"
> > 
> > 
> > Could you post more information like GPU numbers, dataset size? It will be helpful for us to debug it.
> 
> Thank you for your attention.
> Below is my information:
> GPU: GeForce RTX 3070, CUDA: cuda_11.2.r11.2/compiler.29558016_0, Driver Version: 460.91.03, Pytorch: 1.9
> 
> Dataset infomation:
> labeled train imgs: 1798, labeled val imgs: 201, unlabeled imgs: 7000
> 
> Custom config infomation(soft_teacher_faster_rcnn_r50_caffe_fpn_custom_full.py):
> _base_="base.py"
> 
> data = dict(
> samples_per_gpu=8,
> workers_per_gpu=8,
> train=dict(
> 
> ```
>     sup=dict(
> 
>         ann_file="data/coco/annotations/instances_train2017.json",
>         img_prefix="data/coco/train2017/",
> 
>     ),
>     unsup=dict(
> 
>         ann_file="data/coco/annotations/instances_unlabeled2017.json",
>         img_prefix="data/coco/unlabeled2017/",
> 
>     ),
> ),
> sampler=dict(
>     train=dict(
>         sample_ratio=[1, 1],
>     )
> ),
> ```
> 
> )
> 
> semi_wrapper = dict(
> train_cfg=dict(
> unsup_weight=2.0,
> )
> )
> 
> lr_config = dict(step=[2400 * 4, 3200 * 4])
> runner = dict(_delete_=True, type="IterBasedRunner", max_iters=3600 * 4)

**Comment by duany049** [comment]
> > When I use my custom data, raise error: "assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}""
> > then I print the length info, =====len of indices is 29336 - offset: 0 - len self 58640
> > below is the detail error info, Please help me.
> > Traceback (most recent call last):
> > File "tools/train.py", line 198, in
> > main()
> > File "tools/train.py", line 193, in main
> > meta=meta,
> > File "/home/swap/project/SoftTeacher/ssod/apis/train.py", line 205, in train_detector
> > runner.run(data_loaders, cfg.workflow)
> > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in run
> > iter_loaders = [IterLoader(x) for x in data_loaders]
> > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 117, in
> > iter_loaders = [IterLoader(x) for x in data_loaders]
> > File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 23, in **init**
> > self.iter_loader = iter(self._dataloader)
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in **iter**
> > return _MultiProcessingDataLoaderIter(self)
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 764, in **init**
> > self._try_put_index()
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
> > index = self._next_index()
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
> > return next(self._sampler_iter) # may raise StopIteration
> > File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in **iter**
> > for idx in self.sampler:
> > File "/home/swap/project/SoftTeacher/ssod/datasets/samplers/semi_sampler.py", line 186, in **iter**
> > assert len(indices) == len(self), f"{indices} not equal {len(self)} while offset is: {offset}"
> 
> Could you post more information like GPU numbers, dataset size? It will be helpful for us to debug it.

I fixed this problem by configuring the development environment.  Thank you all the same

**Comment by winnerziqi** [comment]
hello, how did you solve the bug, and now I have the same bug
