### ISSUE TITLE
Question about compute_uncertainty_with_aug

### ISSUE THREAD

**Issue by lhphanto** [microsoft/SoftTeacher#93]
Hi,

I am trying to understand how `compute_uncertainty_with_aug` works. And specifically `self.teacher.roi_head.simple_test_bboxes`.
So the input is `img_metas`- which contains the original input image data, `auged_proposal_list` is the jittered bboxes?
I remember in the paper section 3.3 it mentions that ` ... **feed the jittered box into the
teacher model** to obtain the refined box...`   so the rpn is skipped here? i.e, the jittered boxes here was pretended to be the proposals came from RPN?

The reason I am asking is I am trying to apply the soft teacher methodology for SSD, which doesn't have a RPN.  And I am wondering how to calculate the variance accordingly.

Thanks!

**Comment by MendelXu** [comment]
I think it is hard to do that for SSD as there is no ROI pooling part for SSD.  You can refer to https://github.com/microsoft/SoftTeacher/issues/44#issuecomment-937998825 for detailed discussion on this problem.
