### ISSUE TITLE
Have you tried single stage network?

### ISSUE THREAD

**Issue by Yuuuuuuuuuuuuuuuuuummy** [microsoft/SoftTeacher#95]
Hi,

I wonder whether this method could be applied to the single stage object detection(SSOD). I noticed many semi-supervised object detection method mentioned that their method could be applied to SSOD, but nobody give the experiment.

Maybe the lower recall of the teacher model is one of the biggest problems in the training.  Due to there is no RPN network to ensure these proposals. Dont no have you tried SSOD and what's your opinion.

Thx

**Comment by MendelXu** [comment]
I have tried it on Retinanet. And from my experiments, pretraining the detector on the labeled data before the semisupervised training can make it progress better.

**Comment by lhphanto** [comment]
Hi @MendelXu,

I am very interested in how you tried Retinanet? Based on https://github.com/microsoft/SoftTeacher/issues/93, I thought it is a little bit difficult to calculate variance for the pseudo boxes for single-staged detectors?

Thanks!

**Comment by MendelXu** [comment]
> Hi @MendelXu,
> 
> I am very interested in how you tried Retinanet? Based on #93, I thought it is a little bit difficult to calculate variance for the pseudo boxes for single-staged detectors?
> 
> Thanks!

No. As discussed in #93, I didn't implement the variance computation part for single stage detector and just try to keep consistency between the student and the teacher by the weighting mechanisms.

**Comment by lhphanto** [comment]
Hi @MendelXu ,

Thanks for the clarification! May I know more details of what you mean by `keep consistency between by weighting mechanisms`? Is it using FixMatch for single-staged network?
Also, wondering if you already did some experiments to use data augmentation (instead of the jittering boxes) to estimate box regression variance uncertainty?

**Comment by Yuuuuuuuuuuuuuuuuuummy** [comment]
> I have tried it on Retinanet. And from my experiments, pretraining the detector on the labeled data before the semisupervised training can make it progress better.

Hi Mengde,

Could you please share some experiment result on RetinaNet, like how much can this method improve?

Any result can be a reference for me！ thx

**Comment by MendelXu** [comment]
> Hi @MendelXu ,
> 
> Thanks for the clarification! May I know more details of what you mean by `keep consistency between by weighting mechanisms`? Is it using FixMatch for single-staged network? Also, wondering if you already did some experiments to use data augmentation (instead of the jittering boxes) to estimate box regression variance uncertainty?

For the first question, It is like a weak version of our method as there is no ROI pooling step in the single-staged detector but I didn't finish it for some reason. For the second question, no, I didn't try that as the cost may be a little high for the online pseudo label generation process. You may try it with an offline method.
>Hi Mengde,

>Could you please share some experiment result on RetinaNet, like how much can this method improve?

> Any result can be a reference for me！ thx

Sorry, I didn't finish the experiments fully and the results are not referential...
