### ISSUE TITLE
some questions about model update

### ISSUE THREAD

**Issue by leijie0106** [microsoft/SoftTeacher#97]
第一个问题：SoftTeacher.py文件中的forward_train方法返回了监督损失和无监督损失，请问像论文中的无监督损失和监督损失加权计算的代码在哪里呢？
第二个问题：mmcv中的optimizerhook中可以进行优化器的调用，以及模型的优化更新，请问SoftTeacher模型在计算了损失值后的模型参数更新的代码在哪里呢？
感谢您的工作

**Comment by MendelXu** [comment]
1. loss的权重是通过unsup_weight给的，然后不同部分的loss求和是在mmdetection里面https://github.com/open-mmlab/mmdetection/blob/374d4c0bed3e3c01e2988213b54310500479e3df/mmdet/models/detectors/base.py#L239
2. 第二个问题模型参数的更新就是在optimizerhook里面实现的，不太明白你是想问什么？

**Comment by leijie0106** [comment]
十分感谢，我明白了。
